### ISSUE TITLE
出力ページにISBN10とISBN13の両方を出力するようにする

### ISSUE THREAD

**Issue by StealthMajor2020** [suwatamon/IsbnCover#14]
出力ページにISBN10とISBN13の両方を出力するようにする。
↓
TODOリスト

両方の形式をtemplateデータに出力する
　✗templateデータをHTMLに出力する
両方の形式をパラメーターとして受け取れるようにする
入力されたISBNの形式を10か13か判定する
10の場合13の形式に変換する
13の場合10の形式に変換する

**Comment by suwatamon** [comment]
「両方の形式をtemplateデータに出力する」をテストするためにgenerateHTML  を分解する

1. テンプレートを作る
1. 引数で与えられたISBNに基づいて、テンプレートに代入する構造体を作る
1. テンプレートに基づいたHTMLを生成する

**Comment by StealthMajor2020** [comment]
来週は3をやる（2021/02/28）
