### ISSUE TITLE
数字認識でISBNを解析する

### ISSUE THREAD

**Issue by suwatamon** [suwatamon/IsbnCover#3]
Canvas 要素に書いた数字を使って、バーコードなどと同じように処理させる

**Comment by StealthMajor2020** [comment]
jpegの中間ファイル名が決め打ちなのが気に食わない

**Comment by suwatamon** [comment]
書き換えの方針

- numrecog.py
 1. 標準入力から受け取って、標準出力に返すようにする

**Comment by StealthMajor2020** [comment]
2020/02/24 メモ
ボタンの場所をキャンバスの上にしたい。
→htmlの中に<style>を書くとシンタックスハイライトが壊れる。
→cssとしてファイルにくくりだすと読み込めない。

**Comment by suwatamon** [comment]
css はファイルを返す用の handle を別途登録の必要があった。
